### ISSUE TITLE
NullPointerException in JAXBContext creation

### ISSUE THREAD

**Issue by noskill** [eclipse-ee4j/jaxb-api#214]
openjdk version "17.0.1" 2021-10-19 LTS
OpenJDK Runtime Environment Microsoft-28056 (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Microsoft-28056 (build 17.0.1+12-LTS, mixed mode)

Nullpointer is dew to module having null name. I am not sure if it's jaxb runtime's fault.

        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/java.lang.module.Configuration.findModule(Configuration.java:548)
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:220)
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:632)
        at java.base/java.lang.Package.getPackageInfo(Package.java:432)
        at java.base/java.lang.Package.getAnnotation(Package.java:458)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.annotation.RuntimeInlineAnnotationReader.getPackageAnnotation(RuntimeInlineAnnotationReader.java:101)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.annotation.RuntimeInlineAnnotationReader.getPackageAnnotation(RuntimeInlineAnnotationReader.java:29)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.TypeInfoImpl.parseElementName(TypeInfoImpl.java:96)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.ClassInfoImpl.<init>(ClassInfoImpl.java:98)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.RuntimeClassInfoImpl.<init>(RuntimeClassInfoImpl.java:70)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.createClassInfo(RuntimeModelBuilder.java:76)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.createClassInfo(RuntimeModelBuilder.java:46)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.getClassInfo(ModelBuilder.java:214)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:66)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:46)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.getClassInfo(ModelBuilder.java:184)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:61)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:46)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.getTypeInfo(ModelBuilder.java:332)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.getTypeInfo(ModelBuilder.java:347)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:413)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:251)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:77)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1111)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:140)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:274)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:263)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:243)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.ContextFinder.find(ContextFinder.java:407)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
        ...

**Comment by noskill** [comment]
It's due to custom classloader
