### ISSUE TITLE
ModelUtil error in JAXBContext.newInstance()

### ISSUE THREAD

**Issue by jimma** [eclipse-ee4j/jaxb-api#224]
There are jakarta.xml.bind:jakarta.xml.bind-api:jar:3.0.1 and org.glassfish.jaxb:jaxb-core:jar:3.0.2 in the flat classpath. 
When the javax.xml.namespace.QName is passed to JAXBContext.newInstance() to create JAXBContenxt, it throws the follow error :  

Caused by: jakarta.xml.bind.JAXBException: Package javax.xml.namespace with Jakarta XML Binding class javax.xml.namespace.QName defined in a module java.xml must be open to at least jakarta.xml.bind module.
	at jakarta.xml.bind.ModuleUtil.delegateAddOpensToImplModule(ModuleUtil.java:132)
	at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:270)
	at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:263)
	at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:395)
	at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
	at org.apache.cxf.common.jaxb.JAXBContextCache$2.run(JAXBContextCache.java:339)
	at org.apache.cxf.common.jaxb.JAXBContextCache$2.run(JAXBContextCache.java:337)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.cxf.common.jaxb.JAXBContextCache.createContext(JAXBContextCache.java:337)
	at org.apache.cxf.common.jaxb.JAXBContextCache.getCachedContextAndSchemas(JAXBContextCache.java:245)
	at org.apache.cxf.jaxb.JAXBDataBinding.createJAXBContextAndSchemas(JAXBDataBinding.java:499)
	at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:358)`

It looks the ModelUtil has issues to check if there is other module has the implementation [in these lines](https://github.com/eclipse-ee4j/jaxb-api/blob/3.0.1/jaxb-api/src/main/mr-jar/jakarta/xml/bind/ModuleUtil.java#L115-L119) : 
Should it return when impModule` and `jaxbModule` is the same here ? Or even skip this `ModelUtils` operations from `ContextFinder` when it says it's flat classpath ?

**Comment by jimma** [comment]
Hi @lukasj , can you please have a look at this issue ? If this is a bug, I'll try to send a PR to fix.

**Comment by lukasj** [comment]
Do you have some small reproducible test case?

**Comment by jimma** [comment]
@lukasj  Here is the reproducer : https://github.com/jimma/jaxb-modelutil-error
I forgot to mention this error happens on JDK17. My local JDK version is : `openjdk version "17.0.1" 2021-10-19'

**Comment by lukasj** [comment]
thanks! Your reproducer helped me to find another issue - both should be fixed in 4.0.0. Do you need a backport to 3.x? If so, it will take some time (after 4.0.0/EE 10 is done)

**Comment by jimma** [comment]
> Do you need a backport to 3.x? If so, it will take some time (after 4.0.0/EE 10 is done)

Yes. It would be great to backport to 3.x and have a release soon.  Thanks.
