### ISSUE TITLE
Filename clash when locating resource bundle messages

### ISSUE THREAD

**Issue by dmatej** [eclipse-ee4j/jaxb-api#262]
In example this block in the `Messages` class results in an attempt to use directly the `Messages` class as a `ResourceBundle` which it doesn't implement. The original idea was probably to load the `Messages.properties` file in the same package. Same result is on JDK11, 17, 18.

```
    static String format( String property, Object[] args ) {
        String text = ResourceBundle.getBundle(Messages.class.getName()).getString(property);
        return MessageFormat.format(text,args);
    }
```

```
java.util.MissingResourceException: Can't find bundle for base name jakarta.xml.bind.Messages, locale cs_CZ
at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2045)
at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1683)
at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1586)
at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549)
at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:858)
at jakarta.xml.bind.Messages.format(Messages.java:41)
at jakarta.xml.bind.Messages.format(Messages.java:22)
at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:144)
at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:340)
at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:392)
at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:349)
......
Caused by: java.lang.ClassCastException: jakarta.xml.bind.Messages cannot be cast to ResourceBundle
at java.base/java.util.ResourceBundle$Control.newBundle0(ResourceBundle.java:3211)
at java.base/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3151)
at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1984)
at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1770)
at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1656)
... 47 more
```

**Comment by lukasj** [comment]
JDK/RBundle.getBundle checks 2 file formats - first java.class leading to CCE which is caught and another run with java.properties which finds the required bundle and continues

Why do you believe this is a problem?

**Comment by dmatej** [comment]
> JDK/RBundle.getBundle checks 2 file formats - first java.class leading to CCE which is caught and another run with java.properties which finds the required bundle and continues
> 
> Why do you believe this is a problem?

It is not caught. The context is bit specific, I broke the classpath by some changes, but the exception is lost and replaced by this MRE. The Messages.properties file is completely ignored.

```
[2022-06-21T14:53:50.660+02:00] [glassfish 7.0] [INFO] [NCLS-REST-00003] [jakarta.enterprise.admin.rest] [tid: _ThreadID=65 _ThreadName=admin-listener(2)] [timeMillis: 1655816030660] [levelValue: 800] [[
An error occurred while processing the request. Please see the server logs for details.
java.util.MissingResourceException: Can't find bundle for base name jakarta.xml.bind.Messages, locale cs_CZ
at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2045)
at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1683)
at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1586)
at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549)
at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:858)
at jakarta.xml.bind.Messages.format(Messages.java:41)
at jakarta.xml.bind.Messages.format(Messages.java:22)
at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:144)
at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:340)
at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:392)
at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:349)
at org.glassfish.jersey.server.wadl.internal.WadlApplicationContextImpl.getJAXBContextFromWadlGenerator(WadlApplicationContextImpl.java:121)
at org.glassfish.jersey.server.wadl.internal.WadlApplicationContextImpl.isJaxbImplAvailable(WadlApplicationContextImpl.java:270)
at org.glassfish.jersey.server.wadl.WadlFeature.configure(WadlFeature.java:65)
at org.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:728)
at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:647)
at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:832)
at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:345)
at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:310)
at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:309)
at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:274)
at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:261)
at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.<init>(GrizzlyHttpContainer.java:310)
at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainerProvider.createContainer(GrizzlyHttpContainerProvider.java:37)
at org.glassfish.jersey.server.ContainerFactory.createContainer(ContainerFactory.java:58)
at org.glassfish.admin.rest.adapter.RestAdapter.getJerseyContainer(RestAdapter.java:283)
at org.glassfish.admin.rest.adapter.RestAdapter.exposeContext(RestAdapter.java:276)
at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:152)
at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:440)
at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassCastException: jakarta.xml.bind.Messages cannot be cast to ResourceBundle
at java.base/java.util.ResourceBundle$Control.newBundle0(ResourceBundle.java:3211)
at java.base/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3151)
at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1984)
at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1770)
at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1656)
... 47 more
]]

[2022-06-21T14:53:50.841+02:00] [glassfish 7.0] [INFO] [NCLS-REST-00003] [jakarta.enterprise.admin.rest] [tid: _ThreadID=66 _ThreadName=admin-listener(3)] [timeMillis: 1655816030841] [levelValue: 800] [[
```

**Comment by dmatej** [comment]
> JDK/RBundle.getBundle checks 2 file formats - first java.class leading to CCE which is caught and another run with java.properties which finds the required bundle and continues
> 
> Why do you believe this is a problem?

It is not caught. The context is bit specific, I broke the classpath by some changes, but the exception is lost and replaced by this MRE. The Messages.properties file is completely ignored.

```
[2022-06-21T14:53:50.660+02:00] [glassfish 7.0] [INFO] [NCLS-REST-00003] [jakarta.enterprise.admin.rest] [tid: _ThreadID=65 _ThreadName=admin-listener(2)] [timeMillis: 1655816030660] [levelValue: 800] [[
An error occurred while processing the request. Please see the server logs for details.
java.util.MissingResourceException: Can't find bundle for base name jakarta.xml.bind.Messages, locale cs_CZ
at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2045)
at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1683)
at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1586)
at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549)
at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:858)
at jakarta.xml.bind.Messages.format(Messages.java:41)
at jakarta.xml.bind.Messages.format(Messages.java:22)
at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:144)
at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:340)
at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:392)
at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:349)
at org.glassfish.jersey.server.wadl.internal.WadlApplicationContextImpl.getJAXBContextFromWadlGenerator(WadlApplicationContextImpl.java:121)
at org.glassfish.jersey.server.wadl.internal.WadlApplicationContextImpl.isJaxbImplAvailable(WadlApplicationContextImpl.java:270)
at org.glassfish.jersey.server.wadl.WadlFeature.configure(WadlFeature.java:65)
at org.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:728)
at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:647)
at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:832)
at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:345)
at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:310)
at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:309)
at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:274)
at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:261)
at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.<init>(GrizzlyHttpContainer.java:310)
at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainerProvider.createContainer(GrizzlyHttpContainerProvider.java:37)
at org.glassfish.jersey.server.ContainerFactory.createContainer(ContainerFactory.java:58)
at org.glassfish.admin.rest.adapter.RestAdapter.getJerseyContainer(RestAdapter.java:283)
at org.glassfish.admin.rest.adapter.RestAdapter.exposeContext(RestAdapter.java:276)
at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:152)
at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:440)
at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassCastException: jakarta.xml.bind.Messages cannot be cast to ResourceBundle
at java.base/java.util.ResourceBundle$Control.newBundle0(ResourceBundle.java:3211)
at java.base/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3151)
at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1984)
at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1770)
at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1656)
... 47 more
]]

[2022-06-21T14:53:50.841+02:00] [glassfish 7.0] [INFO] [NCLS-REST-00003] [jakarta.enterprise.admin.rest] [tid: _ThreadID=66 _ThreadName=admin-listener(3)] [timeMillis: 1655816030841] [levelValue: 800] [[
```

**Comment by dmatej** [comment]
Hmm, true, then ... for some reason the property file is really ignored. That could be caused by something in GlassFish's classloaders and RB then uses as a cause the exception it catched when it tried to load the bundle by all usable ways.
I will close it for now, despite it seems that using same name for a class and for the property file is not a lucky solution.
